name: Lesson 3

on:
  push:

jobs:

  learning-steps:
    runs-on: ubuntu-latest

    steps:

      - run: echo "Step 1 starting"

      - run: echo "Step 2 running"

      - run: echo "Step 3 complete"
