name: Lesson 3

on:
  push:

jobs:

  learning-steps:
    runs-on: ubuntu-latest

    steps:

      - name: Welcome Step
        run: echo "Robot started"

      - name: Create Folder
        run: mkdir my-folder

      - name: Show Files
        run: ls

      - name: Finish
        run: echo "Workflow complete"
